### ISSUE TITLE
Apple Tv support

### ISSUE THREAD

**Issue by marima84** [ericmatte/ad-media-lights-sync#1]
Hi,
thank you for your app, I would like to ask if it would be possible to implement Apple TV support to your code [hass-atv-beta](https://github.com/postlund/hass-atv-beta).
The available attribute I can get is this:
`entity_picture: /api/media_player_proxy/media_player.soggiorno?token=[TOKEN REMOVED]cache=https://is1-ssl.mzstatic.com/image/thumb/Music128/v4/15/21/7f/15217f17-0e8a-e1b9-d5e8-45487b4e53ad/source/600x600bb.jpg`

I don't know if log error could be helpful:

```
2020-04-20 14:20:26.490227 WARNING media_lights_sync: ------------------------------------------------------------
2020-04-20 14:20:26.488091 WARNING media_lights_sync: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 777, in worker
    funcref(entity, attr, old_state, new_state,
  File "/config/appdaemon/apps/ad-media-lights-sync/media_lights_sync.py", line 26, in change_lights_color
    rgb_colors = self.get_colors(newUrl)
  File "/config/appdaemon/apps/ad-media-lights-sync/media_lights_sync.py", line 40, in get_colors
    fd = urlopen(url)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 509, in open
    req = Request(fullurl, data)
  File "/usr/lib/python3.8/urllib/request.py", line 328, in __init__
    self.full_url = url
  File "/usr/lib/python3.8/urllib/request.py", line 354, in full_url
    self._parse()
  File "/usr/lib/python3.8/urllib/request.py", line 383, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'playing'

2020-04-20 14:20:26.482535 WARNING media_lights_sync: ------------------------------------------------------------
2020-04-20 14:20:26.480592 WARNING media_lights_sync: Worker Ags: {'id': '92741f2778e54bc9be97b46dec5c5818', 'name': 'media_lights_sync', 'objectid': '55f675cdb87e4e959f8458081a69335f', 'type': 'state', 'function': >, 'attribute': 'state', 'entity': 'media_player.soggiorno', 'new_state': 'playing', 'old_state': 'paused', 'pin_app': True, 'pin_thread': 1, 'kwargs': {'attribute': None, '__thread_id': 'thread-1'}}
2020-04-20 14:20:26.477225 WARNING media_lights_sync: Unexpected error in worker for App media_lights_sync:
2020-04-20 14:20:26.474623 WARNING media_lights_sync: ------------------------------------------------------------
2020-04-20 14:20:26.305641 WARNING media_lights_sync: ------------------------------------------------------------
2020-04-20 14:20:26.303295 WARNING media_lights_sync: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 777, in worker
    funcref(entity, attr, old_state, new_state,
  File "/config/appdaemon/apps/ad-media-lights-sync/media_lights_sync.py", line 26, in change_lights_color
    rgb_colors = self.get_colors(newUrl)
  File "/config/appdaemon/apps/ad-media-lights-sync/media_lights_sync.py", line 40, in get_colors
    fd = urlopen(url)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 509, in open
    req = Request(fullurl, data)
  File "/usr/lib/python3.8/urllib/request.py", line 328, in __init__
    self.full_url = url
  File "/usr/lib/python3.8/urllib/request.py", line 354, in full_url
    self._parse()
  File "/usr/lib/python3.8/urllib/request.py", line 383, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'paused'

2020-04-20 14:20:26.297838 WARNING media_lights_sync: ------------------------------------------------------------
2020-04-20 14:20:26.295595 WARNING media_lights_sync: Worker Ags: {'id': '92741f2778e54bc9be97b46dec5c5818', 'name': 'media_lights_sync', 'objectid': '55f675cdb87e4e959f8458081a69335f', 'type': 'state', 'function': >, 'attribute': 'state', 'entity': 'media_player.soggiorno', 'new_state': 'paused', 'old_state': 'playing', 'pin_app': True, 'pin_thread': 1, 'kwargs': {'attribute': None, '__thread_id': 'thread-1'}}
2020-04-20 14:20:26.292221 WARNING media_lights_sync: Unexpected error in worker for App media_lights_sync:
2020-04-20 14:20:26.288435 WARNING media_lights_sync: ------------------------------------------------------------
2020-04-20 14:20:24.034111 WARNING media_lights_sync: ------------------------------------------------------------
2020-04-20 14:20:24.031508 WARNING media_lights_sync: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 777, in worker
    funcref(entity, attr, old_state, new_state,
  File "/config/appdaemon/apps/ad-media-lights-sync/media_lights_sync.py", line 26, in change_lights_color
    rgb_colors = self.get_colors(newUrl)
  File "/config/appdaemon/apps/ad-media-lights-sync/media_lights_sync.py", line 40, in get_colors
    fd = urlopen(url)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 509, in open
    req = Request(fullurl, data)
  File "/usr/lib/python3.8/urllib/request.py", line 328, in __init__
    self.full_url = url
  File "/usr/lib/python3.8/urllib/request.py", line 354, in full_url
    self._parse()
  File "/usr/lib/python3.8/urllib/request.py", line 383, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'playing'
```

I that is not possible don't mind.. I thank you anyway for your hard work sor the community :)

Regards
Mark

**Comment by ericmatte** [comment]
Hi @marima84,

> I would like to ask if it would be possible to implement Apple TV support to your code hass-atv-beta.

Yes, that is definitively possible! I don't personally own an Apple TV, but I don't think that this error would be too complicated to resolve with a little bit of help from your side.

---

It's seems that the app is unable to correctly listen to your `entity_picture`.
When checking your error log, we can see `ValueError: unknown url type: 'playing'`, which is the current state of your media_player and not the picture url.

The value of url should be an URL corresponding to your thumbnail image, which in your case would be `/api/media_player_proxy/media_player.soggiorno?token=[TOKEN REMOVED]cache=https://is1-ssl.mzstatic.com/image/thumb/Music128/v4/15/21/7f/15217f17-0e8a-e1b9-d5e8-45487b4e53ad/source/600x600bb.jpg`

Could you please try adding `photo_attribute` to your `apps.yaml` config, and send me the output?
```yaml
media_lights_sync:
  # ...
  photo_attribute: "entity_picture" # you can also try with "entity_picture_local"
```

Also, I see that for your Apple TV, the url is relative which will need to have the url to your Home Assistant as the prefix in order for it to work.
I will have to update the code in order to add that (PRs are also welcome 🙂).

In my case, my ChromeCast was giving me and absolute URL to their CDN, so I didn't need to add my HA_URL: https://i.scdn.co/image/ab67616d00001e02660ee24281a547103f466ff5

**Comment by marima84** [comment]
Thank you for your replay.
I tried to do as you suggest, let me show you my config maybe can help a bit.

my apple tv expose the following attribute
![Schermata 2020-04-20 alle 22 35 21](https://user-images.githubusercontent.com/41524061/79797528-b2009f00-8357-11ea-9e07-b4059bc35080.png)

since it don't have a clear URL I thought to create a sensor with a cleansed URL:
```
- platform: template
  sensors:
    cover_appletv:
      entity_id: media_player.appletv
      value_template: "{{ state_attr('media_player.appletv', 'entity_picture')[122:] }}"
```
![Schermata 2020-04-20 alle 22 40 00](https://user-images.githubusercontent.com/41524061/79797646-e96f4b80-8357-11ea-956b-e173bab4a294.png)
The URL is working and show me the correct thumbnail image.

apps.yaml
```
media_lights_sync:
  module: media_lights_sync
  class: MediaLightsSync
  media_player: media_player.appletv
  photo_attribute: sensor.cover_appletv

  condition:
    entity: input_boolean.led_stripe_on
    state: "on"
  lights:
    - light.led_stripe_divano
```

but still I have the following errors:
```
2020-04-20 22:33:17.074692 WARNING media_lights_sync: ------------------------------------------------------------
2020-04-20 22:33:17.072490 WARNING media_lights_sync: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 145, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 276, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/ad-media-lights-sync/media_lights_sync.py", line 20, in initialize
    self.listen_state(self.change_lights_color, self.args["media_player"], self.args.get("photo_attribute", "entity_picture"))
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 191, in inner_sync_wrapper
    f = run_coroutine_threadsafe(self, coro(self, *args, **kwargs))
TypeError: listen_state() takes from 2 to 3 positional arguments but 4 were given

2020-04-20 22:33:17.068647 WARNING media_lights_sync: ------------------------------------------------------------
2020-04-20 22:33:17.066771 WARNING media_lights_sync: Worker Ags: {}
2020-04-20 22:33:17.064450 WARNING media_lights_sync: Unexpected error in worker for App media_lights_sync:
2020-04-20 22:33:17.061796 WARNING media_lights_sync: ------------------------------------------------------------
```

Thanks
Mark

**Comment by ericmatte** [comment]
> since it don't have a clear URL I thought to create a sensor with a cleansed URL

Great idea!
However, the way this app is currently working is that it listen on a specific attribute on the `media_player`, thus not working with `sensor.cover_appletv`.
I am currently working on a way to specify the `ha_url`, so you will not have to add the template sensor anymore.

Try with this config `photo_attribute: "entity_picture"`:
```yaml
media_lights_sync:
  module: media_lights_sync
  class: MediaLightsSync
  media_player: media_player.appletv
  photo_attribute: "entity_picture"
  condition:
    entity: input_boolean.led_stripe_on
    state: "on"
  lights:
    - light.led_stripe_divano
```
And let me know what is the ouput.

**Comment by ericmatte** [comment]
Also, if you test this url manually, does it works?:
`https://your-ha-url/api/media_player_proxy/media_player.soggiorno?token=[TOKEN REMOVED]cache=https://is1-ssl.mzstatic.com/image/thumb/Music128/v4/15/21/7f/15217f17-0e8a-e1b9-d5e8-45487b4e53ad/source/600x600bb.jpg`

Where `https://your-ha-url`  is the proper url to your config (with https or http if you don't use a secure url).

**Comment by ericmatte** [comment]
@marima84, I've just updated the app on the `master` branch. Could you try updating it to the `master` version?
![image](https://user-images.githubusercontent.com/9013072/79803896-e7de5d00-8330-11ea-9e30-a225bf3d0115.png)

And try with a similar config to this:
```yaml
media_lights_sync:
  module: media_lights_sync
  class: MediaLightsSync
  media_player: media_player.appletv
  photo_attribute: "entity_picture"
  ha_url: your_url
  condition:
    entity: input_boolean.led_stripe_on
    state: "on"
  lights:
    - light.led_stripe_divano
```

**Comment by marima84** [comment]
> And try with a similar config to this:
> 
> ```yaml
> media_lights_sync:
>   module: media_lights_sync
>   class: MediaLightsSync
>   media_player: media_player.appletv
>   photo_attribute: "entity_picture"
>   ha_url: your_url
>   condition:
>     entity: input_boolean.led_stripe_on
>     state: "on"
>   lights:
>     - light.led_stripe_divano
> ```

Super!
With this last update and config now it's working like a charm :)
Thank you!

Mark

**Comment by marima84** [comment]
@ericmatte so with your update the URL sensor i've created it's useless... nevermind it was funny to learn how to cut a string in Jinja...

**Comment by ericmatte** [comment]
Great! Glad to hear that it is now working for you :)

I've updated the app with the according changes to the version [**v0.2.0**](https://github.com/ericmatte/ad-media-lights-sync/releases/tag/v0.2.0); you can now update it to this version in HACS in order to be in sync with the futur releases.
