### ISSUE TITLE
compile_error

### ISSUE THREAD

**Issue by marima84** [ericmatte/ad-media-lights-sync#16]
**Describe the bug**
After upgrading to aTV14 and [pyatv](https://github.com/postlund/pyatv) component the app is not working anymore.

**Screenshots or error stack trace**

Appdaemon log when starting up
```
2020-10-08 10:46:39.279923 WARNING Error: ------------------------------------------------------------
2020-10-08 10:46:39.281562 WARNING Error: Unexpected error loading module: /config/appdaemon/apps/ad-media-lights-sync/media_lights_sync.py:
2020-10-08 10:46:39.282943 WARNING Error: ------------------------------------------------------------
2020-10-08 10:46:39.302107 WARNING Error: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 875, in check_app_updates
    await utils.run_in_executor(self, self.read_app, mod["name"], mod["reload"])
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 290, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 668, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/appdaemon/apps/ad-media-lights-sync/media_lights_sync.py", line 8, in <module>
    from PIL import Image
  File "/usr/lib/python3.8/site-packages/PIL/Image.py", line 94, in <module>
    from . import _imaging as core
ImportError: Error loading shared library libtiff.so.5: No such file or directory (needed by /usr/lib/python3.8/site-packages/PIL/_imaging.cpython-38-arm-linux-gnueabihf.so)
2020-10-08 10:46:39.303928 WARNING Error: ------------------------------------------------------------
2020-10-08 10:46:39.305606 WARNING AppDaemon: Removing associated apps:
2020-10-08 10:46:39.307003 WARNING AppDaemon: media_lights_sync
```

**Environment versions:**
 - ad-media-lights-sync: v0.4.0
 - Home Assistant: 0.115.6
 - AppDaemon: 0.3.1

Thank you for checking.

Mark

**Comment by marima84** [comment]
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 900, in worker
    funcref(
  File "/config/appdaemon/apps/ad-media-lights-sync/media_lights_sync.py", line 30, in change_lights_color
    rgb_colors = self.get_colors(self.format_ha_url(newUrl))
  File "/config/appdaemon/apps/ad-media-lights-sync/media_lights_sync.py", line 55, in get_colors
    fd = urlopen(url)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1379, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: 

2020-10-08 13:13:42.168168 WARNING media_lights_sync: ------------------------------------------------------------
2020-10-08 13:13:42.166894 WARNING media_lights_sync: Worker Ags: {'id': '375a1330331c487fba88b0c44711854e', 'name': 'media_lights_sync', 'objectid': '571fe5fde0f74b259783cbf28a49cc5d', 'type': 'state', 'function': >, 'attribute': 'entity_picture', 'entity': 'media_player.appletv', 'new_state': '/api/media_player_proxy/media_player.appletv?token=7f594655e96fb26c5e2719c88c81dbfef5f8cd515bdf8f26a74cab595f145cdc&cache=be0c400658b47fb2a6773b532d7a26dac0cb96ae', 'old_state': '/api/media_player_proxy/media_player.appletv?token=7f594655e96fb26c5e2719c88c81dbfef5f8cd515bdf8f26a74cab595f145cdc&cache=70E9E27D-4260-4CB6-B2B1-6187B3A7E18F', 'pin_app': True, 'pin_thread': 1, 'kwargs': {'attribute': 'entity_picture', '__thread_id': 'thread-1'}}
2020-10-08 13:13:42.164654 WARNING media_lights_sync: Unexpected error in worker for App media_lights_sync:
2020-10-08 13:13:42.163247 WARNING media_lights_sync: ------------------------------------------------------------
2020-10-08 13:13:41.474258 WARNING media_lights_sync: ------------------------------------------------------------
2020-10-08 13:13:41.472729 WARNING media_lights_sync: Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve
```

**Comment by ericmatte** [comment]
Hi,

The error seems to be that the Pillow python package is missing from your AppDaemon setup:
```
  File "/config/appdaemon/apps/ad-media-lights-sync/media_lights_sync.py", line 8, in <module>
    from PIL import Image
  File "/usr/lib/python3.8/site-packages/PIL/Image.py", line 94, in <module>
    from . import _imaging as core
ImportError: Error loading shared library libtiff.so.5: No such file or directory (needed by /usr/lib/python3.8/site-packages/PIL/_imaging.cpython-38-arm-linux-gnueabihf.so)
```

Can you make sure that you have the right prerequisites setup on your AppDaemon?
Here: https://github.com/ericmatte/ad-media-lights-sync#prerequisites

It should looks like something similar to this:
```yaml
system_packages:
  - py3-pillow
python_packages:
  - Pillow
init_commands: []
log_level: info
```

**Comment by marima84** [comment]
I've update AppDaemon configuration as follow:
```YAML
system_packages:
  - musl
  - make
  - g++
  - python3-dev
  - build-base
  - jpeg-dev
  - zlib-dev
  - py3-pillow
python_packages:
  - Pillow
init_commands: []
log_level: info
```

But stil not working:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 900, in worker
    funcref(
  File "/config/appdaemon/apps/ad-media-lights-sync/media_lights_sync.py", line 30, in change_lights_color
    rgb_colors = self.get_colors(self.format_ha_url(newUrl))
  File "/config/appdaemon/apps/ad-media-lights-sync/media_lights_sync.py", line 55, in get_colors
    fd = urlopen(url)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1379, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: 

2020-10-17 11:35:03.891238 WARNING media_lights_sync: ------------------------------------------------------------
2020-10-17 11:35:03.890102 WARNING media_lights_sync: Worker Ags: {'id': '5e1d4e7603f3432db57a4ec5b6b67f54', 'name': 'media_lights_sync', 'objectid': '46fa4e3815fb42ccb1780d8d8027a05f', 'type': 'state', 'function': >, 'attribute': 'entity_picture', 'entity': 'media_player.appletv', 'new_state': '/api/media_player_proxy/media_player.appletv?token=acc791b0d11b8f93377c721f29107a8d3c38365b1b9ae5a0280e109fd76fb936&cache=21FD56C9-5B7F-4A42-A458-838CBC88E80C', 'old_state': None, 'pin_app': True, 'pin_thread': 1, 'kwargs': {'attribute': 'entity_picture', '__thread_id': 'thread-1'}}
2020-10-17 11:35:03.888740 WARNING media_lights_sync: Unexpected error in worker for App media_lights_sync:
2020-10-17 11:35:03.887599 WARNING media_lights_sync: ------------------------------------------------------------
```
Any suggeston?
Thanks

Mark

**Comment by ericmatte** [comment]
This seems to be another error related to the URL:
```
  File "/config/appdaemon/apps/ad-media-lights-sync/media_lights_sync.py", line 55, in get_colors
    fd = urlopen(url)
```

I think it is related to your first issue: https://github.com/ericmatte/ad-media-lights-sync/issues/1. Can you make sure that the full URL to your thumbnail image is still working?

Maybe the URL changed with the upgrade to aTV14 and pyatv.
Just to make sure, you also need to have `ha_url` defined in your specific config.

**Comment by marima84** [comment]
Sorry, it was just an error on the App configuration. There was an extra space on the line `ha_url`.
Confirmed that works with TvOS 14 as well.

Thanks for your patiance 
Mark

**Comment by ericmatte** [comment]
My pleasure; enjoy the app :)
