### ISSUE TITLE
Errors in AppDaemon Log/Lights not changing

### ISSUE THREAD

**Issue by fhuebner2** [ericmatte/ad-media-lights-sync#27]
Hello,
I have installed via Hacs and added the config as follows to my apps.yaml:
```yaml
media_lights_sync:
  module: media_lights_sync
  class: MediaLightsSync
  media_player: media_player.google_home_mini
  lights: light.led1_wohnzimmer
  ha_url: https://192.168.1.137:8123
  reset_lights_after: true
  use_saturated_colors: false
  use_current_brightness: false
  condition:
    entity: input_boolean.sync_tv_lights
    state: "on"
```

If I look into the developer Tools,I can see the picture entities changing if I change the song, but light is not changing. Following issues are in the AppDaemon Log:

```bash
AppDaemon: Initializing app media_lights_sync using class MediaLightsSync from module media_lights_sync
2021-02-05 02:34:45.125949 INFO media_lights_sync: Listening for picture changes on 'media_player.google_home_mini'
2021-02-05 02:34:45.132420 INFO AppDaemon: App initialization complete
2021-02-05 02:35:09.381926 WARNING media_lights_sync: ------------------------------------------------------------
2021-02-05 02:35:09.382875 WARNING media_lights_sync: Unexpected error in worker for App media_lights_sync:
2021-02-05 02:35:09.383763 WARNING media_lights_sync: Worker Ags: {'id': '0ae6673be2e249bfa7e8c4daa08478e2', 'name': 'media_lights_sync', 'objectid': 'db58209fdff64019ba2a6ee620469a8f', 'type': 'state', 'function': <bound method MediaLightsSync.change_lights_color of <media_lights_sync.MediaLightsSync object at 0xb4e8e460>>, 'attribute': 'entity_picture_local', 'entity': 'media_player.google_home_mini', 'new_state': '/api/media_player_proxy/media_player.google_home_mini?token=2354807e7a66d2b2c03ea241a1b07dacc667f5b75c256d0c4cde1f4dc8973834&cache=750effe1c450c808', 'old_state': '/api/media_player_proxy/media_player.google_home_mini?token=2354807e7a66d2b2c03ea241a1b07dacc667f5b75c256d0c4cde1f4dc8973834&cache=924d592084ff9f1a', 'pin_app': True, 'pin_thread': 2, 'kwargs': {'attribute': 'entity_picture_local', '__thread_id': 'thread-2'}}
2021-02-05 02:35:09.384670 WARNING media_lights_sync: ------------------------------------------------------------
2021-02-05 02:35:09.403697 WARNING media_lights_sync: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 900, in worker
    funcref(
  File "/config/appdaemon/apps/ad-media-lights-sync/media_lights_sync.py", line 44, in change_lights_color
    self.store_initial_lights_states()
  File "/config/appdaemon/apps/ad-media-lights-sync/media_lights_sync.py", line 67, in store_initial_lights_states
    self.initial_lights_states = [self.get_state(self.lights[i], attribute="all") for i in range(len(self.lights))]
  File "/config/appdaemon/apps/ad-media-lights-sync/media_lights_sync.py", line 67, in <listcomp>
    self.initial_lights_states = [self.get_state(self.lights[i], attribute="all") for i in range(len(self.lights))]
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 195, in inner_sync_wrapper
    f = run_coroutine_threadsafe(self, coro(self, *args, **kwargs))
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 299, in run_coroutine_threadsafe
    result = future.result(self.AD.internal_function_timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/site-packages/appdaemon/adapi.py", line 1392, in get_state
    return await self.AD.state.get_state(self.name, namespace, entity_id, attribute, default, copy, **kwargs)
  File "/usr/lib/python3.8/site-packages/appdaemon/state.py", line 389, in get_state
    raise ValueError("{}: Querying a specific attribute is only possible for a single entity".format(name))
ValueError: media_lights_sync: Querying a specific attribute is only possible for a single entity
2021-02-05 02:35:09.404456 WARNING media_lights_sync: ------------------------------------------------------------
2021-02-05 02:35:09.423361 WARNING media_lights_sync: ------------------------------------------------------------
2021-02-05 02:35:09.424312 WARNING media_lights_sync: Unexpected error in worker for App media_lights_sync:
2021-02-05 02:35:09.425138 WARNING media_lights_sync: Worker Ags: {'id': '87ab009ece19400dbabecee9ea0d2f01', 'name': 'media_lights_sync', 'objectid': 'db58209fdff64019ba2a6ee620469a8f', 'type': 'state', 'function': <bound method MediaLightsSync.change_lights_color of <media_lights_sync.MediaLightsSync object at 0xb4e8e460>>, 'attribute': 'entity_picture', 'entity': 'media_player.google_home_mini', 'new_state': 'https://i.scdn.co/image/ab67616d00001e023797253ef8b94a9e35e1b7c6', 'old_state': 'https://i.scdn.co/image/ab67616d00001e0204a9270e5d53595a1d176779', 'pin_app': True, 'pin_thread': 2, 'kwargs': {'attribute': 'entity_picture', '__thread_id': 'thread-2'}}
2021-02-05 02:35:09.425838 WARNING media_lights_sync: ------------------------------------------------------------
2021-02-05 02:35:09.430778 WARNING media_lights_sync: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 900, in worker
    funcref(
  File "/config/appdaemon/apps/ad-media-lights-sync/media_lights_sync.py", line 44, in change_lights_color
    self.store_initial_lights_states()
  File "/config/appdaemon/apps/ad-media-lights-sync/media_lights_sync.py", line 67, in store_initial_lights_states
    self.initial_lights_states = [self.get_state(self.lights[i], attribute="all") for i in range(len(self.lights))]
  File "/config/appdaemon/apps/ad-media-lights-sync/media_lights_sync.py", line 67, in <listcomp>
    self.initial_lights_states = [self.get_state(self.lights[i], attribute="all") for i in range(len(self.lights))]
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 195, in inner_sync_wrapper
    f = run_coroutine_threadsafe(self, coro(self, *args, **kwargs))
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 299, in run_coroutine_threadsafe
    result = future.result(self.AD.internal_function_timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/site-packages/appdaemon/adapi.py", line 1392, in get_state
    return await self.AD.state.get_state(self.name, namespace, entity_id, attribute, default, copy, **kwargs)
  File "/usr/lib/python3.8/site-packages/appdaemon/state.py", line 389, in get_state
    raise ValueError("{}: Querying a specific attribute is only possible for a single entity".format(name))
ValueError: media_lights_sync: Querying a specific attribute is only possible for a single entity
2021-02-05 02:35:09.431700 WARNING media_lights_sync: ------------------------------------------------------------
```

### Environment versions

- ad-media-lights-sync: 0.6.0
- Home Assistant: 2021.2
- AppDaemon: 0.4.1

Can you help me or fix this issue?

**Comment by ericmatte** [comment]
Hi @fhuebner2,

I think that your problem is that you are not passing only one light, and not a list of lights.

Could you try it again using this config?:
```yaml
media_lights_sync:
  module: media_lights_sync
  class: MediaLightsSync
  media_player: media_player.google_home_mini
  lights:
    - light.led1_wohnzimmer
  ha_url: https://192.168.1.137:8123
  reset_lights_after: true
  use_saturated_colors: false
  use_current_brightness: false
  condition:
    entity: input_boolean.sync_tv_lights
    state: "on"
```

Note the way the `lights:` section is configured like in the [README](https://github.com/ericmatte/ad-media-lights-sync).

**Comment by fhuebner2** [comment]
Nice catch.
Tested and working like this. Thank you!

**Comment by ericmatte** [comment]
Great, glad to hear that :)
