### ISSUE TITLE
Unknown URL Type

### ISSUE THREAD

**Issue by Hypercookie** [ericmatte/ad-media-lights-sync#43]
### Describe the bug

While Syncing the lights there is an error logged ( and the lights wont sync)

### To Reproduce

Use This Config

```
media_lights_sync:
  module: media_lights_sync
  class: MediaLightsSync
  media_player: media_player.<player>
  lights:
    - light.wohnzimmer_lampe_2
    - light.wohnzimmer_lampe_1
    - light.wled
    - light.pc_links
    - light.pc_rechts
  ha_url: <ip>:8123
  reset_lights_after: true
  use_saturated_colors: false
  use_current_brightness: false
  condition:
    entity: input_boolean.sync_lights_wohnzimmer
    state: "on"
```

### Expected behavior

Lights syncing

### Screenshots or error stack trace

```
2021-08-30 21:19:16.403118 INFO media_lights_sync: New picture received from 'media_player.wohnzimmer' (entity_picture)
2021-08-30 21:19:16.419620 WARNING media_lights_sync: ------------------------------------------------------------
2021-08-30 21:19:16.420667 WARNING media_lights_sync: Unexpected error in worker for App media_lights_sync:
2021-08-30 21:19:16.421933 WARNING media_lights_sync: Worker Ags: {'id': '1a68016d493a4b6d8a79064704aaa9e3', 'name': 'media_lights_sync', 'objectid': '8ac7c56312bd45518d56230896d3ad5e', 'type': 'state', 'function': <bound method MediaLightsSync.change_lights_color of <media_lights_sync.MediaLightsSync object at 0x7fb0ddcfa0>>, 'attribute': 'entity_picture', 'entity': 'media_player.wohnzimmer', 'new_state': '/api/media_player_proxy/media_player.wohnzimmer?token=e9a77d64d181201a8e8f54964c80a720a1f2933cb2edfa1192860a22af9c16ce&cache=3dcee92f534ef9fb', 'old_state': '/api/media_player_proxy/media_player.wohnzimmer?token=e9a77d64d181201a8e8f54964c80a720a1f2933cb2edfa1192860a22af9c16ce&cache=10b5490d6a27e975', 'pin_app': True, 'pin_thread': 1, 'kwargs': {'attribute': 'entity_picture', '__thread_id': 'thread-1'}}
2021-08-30 21:19:16.422838 WARNING media_lights_sync: ------------------------------------------------------------
2021-08-30 21:19:16.428977 WARNING media_lights_sync: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/appdaemon/threading.py", line 903, in worker
    funcref(
  File "/config/appdaemon/apps/ad-media-lights-sync/media_lights_sync.py", line 57, in change_lights_color
    rgb_colors = self.get_colors(url)
  File "/config/appdaemon/apps/ad-media-lights-sync/media_lights_sync.py", line 114, in get_colors
    fd = urlopen(url)
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 501, in open
    req = Request(fullurl, data)
  File "/usr/lib/python3.9/urllib/request.py", line 320, in __init__
    self.full_url = url
  File "/usr/lib/python3.9/urllib/request.py", line 346, in full_url
    self._parse()
  File "/usr/lib/python3.9/urllib/request.py", line 375, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/api/media_player_proxy/media_player.wohnzimmer?token=e9a77d64d181201a8e8f54964c80a720a1f2933cb2edfa1192860a22af9c16ce&cache=3dcee92f534ef9fb'
2021-08-30 21:19:16.429838 WARNING media_lights_sync: ------------------------------------------------------------
```

**Comment by Hypercookie** [comment]
Found the Solution after setting everything up again. The IP / URL **needs** to be preceded by http[s] or it wont work.
