### ISSUE TITLE
No module named 'PIL'

### ISSUE THREAD

**Issue by haberda** [ericmatte/ad-media-lights-sync#5]
I added the required system and python packages in the readme but I am getting an error that there is No module named 'PIL'.

2020-04-25 18:38:04.982809 INFO AppDaemon: Loading App Module: media_lights_sync
2020-04-25 18:38:04.988727 WARNING Error: ------------------------------------------------------------
2020-04-25 18:38:04.989301 WARNING Error: Unexpected error loading module: /config/appdaemon/apps/ad-media-lights-sync/media_lights_sync.py:
2020-04-25 18:38:04.989768 WARNING Error: ------------------------------------------------------------
2020-04-25 18:38:04.991170 WARNING Error: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 566, in read_app
    importlib.reload(self.modules[module_name])
KeyError: 'media_lights_sync'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 788, in check_app_updates
    await utils.run_in_executor(self, self.read_app, mod["name"], mod["reload"])
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 276, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 571, in read_app
    self.read_app(file)
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 580, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/appdaemon/apps/ad-media-lights-sync/media_lights_sync.py", line 6, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'

2020-04-25 18:38:04.991598 WARNING Error: ------------------------------------------------------------
2020-04-25 18:38:04.992151 WARNING AppDaemon: Removing associated apps:
2020-04-25 18:38:04.992599 WARNING AppDaemon: media_lights_sync

**Comment by ericmatte** [comment]
It seems that you are missing a dependency.

Please refer to the [Prerequisites](https://github.com/ericmatte/ad-media-lights-sync#prerequisites) section of the README.
Also, make sure to restart AppDaemon after saving changes to that config.

Are you using Home Assistant OS?

What versions are you using for theses?:
- Home Assistant
- AppDaemon

**Comment by haberda** [comment]
My mistake, I added this to my appdaemon.yaml not the config for the homeassistant add-on. Thanks!
