### ISSUE TITLE
"no module name PIL"

### ISSUE THREAD

**Issue by prankousky** [ericmatte/ad-media-lights-sync#7]
Hi,

I just started using `AppDaemon` for my `Home Assistant` a few days ago and this app seems so cool, so I wanted to try it. Unfortunately, it will not work due to missing modules, I assume.

This is my `appdaemon.yaml`

```
appdaemon:
  threads: 10
  plugins:
    HASS:
      type: hass
      ha_url: ""
      token: ""
admin:

api:

# added these lines as in README.me; added the extra "PIL" underneath "Pillow" just as a test, didn't make a difference
system_packages:
  - musl
  - make
  - g++
  - python3-dev
  - build-base
  - jpeg-dev
  - zlib-dev
python_packages:
  - Pillow
  - PIL

log:
  logfile: STDOUT
  errorfile: STDERR
hadashboard:
  dash_url: ""
```

After adding the lines for `ad-media-lights-sync` to my `apps.yaml`, these errors occured

```
2020-05-04 11:07:22.087407 INFO AppDaemon: Loading App Module: /conf/apps/media_lights_sync.py
2020-05-04 11:07:22.095161 WARNING AppDaemon: ------------------------------------------------------------
2020-05-04 11:07:22.095370 WARNING AppDaemon: Unexpected error loading module: /conf/apps/media_lights_sync.py:
2020-05-04 11:07:22.095468 WARNING AppDaemon: ------------------------------------------------------------
2020-05-04 11:07:22.097138 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 2026, in check_app_updates
    self.read_app(mod["name"], mod["reload"])
  File "/usr/local/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 1809, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/conf/apps/media_lights_sync.py", line 6, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
```

I am running AppDaemon in a docker container; do I have to manually install these packages **to** the docker container somehow? I assumed that the lines in `appdaemon.yaml` would automatically take care of this for me, but then it wouldn't be missing the module..?

Thank you in advance for your help :)

**Comment by ericmatte** [comment]
@prankousky please refer to this issue: https://github.com/ericmatte/ad-media-lights-sync/issues/5#issuecomment-619979205

You are correct: have to install those packages directly in your Docker image, not in the `appdaemon.yml` config (that won't do anything).

**Comment by ericmatte** [comment]
@prankousky I've updated the Readme to clarify were to install the dependencies.

I've also added a section for your use case: https://github.com/ericmatte/ad-media-lights-sync/blob/master/README.md#prerequisites

Create a `Dockerfile` like in this updated readme, and build it like so:
```bash
docker build -t my-appdaemon .
```
After that, you should be able to docker run `my-appdaemon` like you usually do.

Let me know if this works, so I can update the readme according to you.

**Comment by prankousky** [comment]
Thank you. I was not able to install `Pillow` via Dockerfile, but `docker exec -it appdaemon_custom /bin/sh`, then `pip install Pillow` and `pip3 install Pillow` (wasn't sure which one was the right one) worked fine :)

**Comment by ericmatte** [comment]
Good, glad to hear that you made it worked :)

The advantage of using a Dockerfile is that you wouldn't have to manually rerun the installation commands if you were to delete your `appdaemon_custom` image from your system.
